In [2]:
import numpy as np

In [3]:
x = np.array([2,3,5,1]) #1D array
x2d = np.array([[1,2,3],[4,5,6]]) #2D array
x3d = np.array([[[1,3],[4,2]],[[2,1],[3,4]]])
print(x)
print(x2d)
print(x3d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]
[[[1 3]
  [4 2]]

 [[2 1]
  [3 4]]]


In [4]:
#sequential matrix, np.arange()and np.lispace
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [5]:
np.arange(0, 10, .2).size

50

In [6]:
np.arange(0, 10, .2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [7]:
np.linspace(0, 15, 5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [8]:
# randomized matrix with np.random
# np.random.rand()
np.random.rand(4,4)#0 to 1
# np.random.randn()# normal distribution
print(np.random.randn(4,4))# normal distribution
#np.random.randint()
print(np.random.randint(-10,10,(3,3)))#random int from -10 to 10
#np.random.uniform()
print(np.random.uniform(0,2,(3,3)))# random unifrom from 0 to 2
#np.random.permutation
print(np.random.permutation([1,2,3,4,5,6,8,9,10]))#random premutation

[[ 0.11370871  1.60039545 -0.23488701 -2.93172936]
 [-0.46686223  1.97819734 -1.98766877 -0.88956316]
 [-0.38962801 -1.8297      0.01289492  0.19159273]
 [ 1.21837179  1.09517037 -0.31597543  1.87131139]]
[[-5 -6  5]
 [-3  8  9]
 [-6  4 -4]]
[[0.99666041 1.15184547 0.40079677]
 [0.56724588 0.51581448 1.63309529]
 [0.72622482 0.19088378 0.94106694]]
[ 4  5  8 10  9  2  1  6  3]


operations

In [9]:
a = np.random.randint(-10,10, (3,3))
b = np.random.randint(-10,10, (3,3))
print(a)
print(b)

[[ 6 -1  0]
 [ 2  4 -8]
 [-7 -5 -7]]
[[ -7  -5  -2]
 [  3   9   0]
 [-10   5  -3]]


In [10]:
# matrix and constant operations
a ** 2 # + - * / ** % //

array([[36,  1,  0],
       [ 4, 16, 64],
       [49, 25, 49]])

In [11]:
# same size matrix operations
print(a + b)
print(a - b)
print(a / b)
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication

[[ -1  -6  -2]
 [  5  13  -8]
 [-17   0 -10]]
[[ 13   4   2]
 [ -1  -5  -8]
 [  3 -10  -4]]
[[-0.85714286  0.2        -0.        ]
 [ 0.66666667  0.44444444        -inf]
 [ 0.7        -1.          2.33333333]]
[[-42   5   0]
 [  6  36   0]
 [ 70 -25  21]]
[[-45 -39 -12]
 [ 78 -14  20]
 [104 -45  35]]


C:\Users\PS3\AppData\Local\Temp\ipykernel_7604\3732709816.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a / b)


In [12]:
# matrix multiplication
np.matmul(a, b) # or np.dot(a, b) or a @ b

array([[-45, -39, -12],
       [ 78, -14,  20],
       [104, -45,  35]])