# Array

In [7]:
import numpy as np
x=[1,2,3,4,5]#list
print(x)
print(type(x))
y=np.array(x)
print(y)#array
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#user input and creating array
l=[]
for i in range(1,6):
    int_1=int(input("Enter:"))
    l.append(int_1)
print(np.array(l))    

[1 2 3 4 5]


In [10]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [14]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Zeros

In [19]:
ar_zero=np.zeros(10)
print(ar_zero)#  1-dimensional
print()
ar_zero1=np.zeros((3,4))
print(ar_zero1)#  2-dimensional

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [20]:
ar_one=np.ones(5)
print(ar_one)

[1. 1. 1. 1. 1.]


# Empty

In [23]:
ar_em=np.empty(0)
print(ar_em)

[]


In [24]:
ar_em=np.empty(10)#bydefalt last array le leta h
print(ar_em)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Range

In [25]:
ar_rn=np.arange(1,11)
print(ar_rn)

[ 1  2  3  4  5  6  7  8  9 10]


# Diagonal

In [26]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linspace

In [28]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


# Random
 - Rand()
 - Randn()
 - Ranf()
 - Randint()# Min Max Total_value

In [29]:
var=np.random.rand(3)
print(var)

[0.94681453 0.27563499 0.40411442]


In [35]:
var1=np.random.rand(3,4)
print(var1)

[[0.91205613 0.15293133 0.79127125 0.95976664]
 [0.9334007  0.05420898 0.72131565 0.55505448]
 [0.12745371 0.70168583 0.12963348 0.66464113]]


In [37]:
var2=np.random.randn(3)
print(var2)

[-0.3094355   1.45160847 -0.3224031 ]


In [39]:
var3=np.random.ranf(4)
print(var3)

[0.71494534 0.03029058 0.01003511 0.49602323]


In [40]:
var4=np.random.randint(1,10,5)
print(var4)

[5 2 7 6 4]
