1-Write a NumPy program to create an array of 10 zeros.

In [9]:
import numpy as np
array1=np.array([0,0,0,0,0,0,0,0,0,0])
print(array1)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
array2=np.zeros(10)
print(array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2-Write a NumPy program to create an array of 10 ones.

In [11]:
x=np.array([1,1,1,1,1,1,1,1,1,1])
print(x)

[1 1 1 1 1 1 1 1 1 1]


3-Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [12]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4-Write a NumPy program to reverse an array (first element becomes the last).

In [14]:
x=np.arange(11,21)
print("Original array is:")
print(x)
#Reverse the array
y=x[::-1]
print("Reverse array is:")
print(y)

Original array is:
[11 12 13 14 15 16 17 18 19 20]
Reverse array is:
[20 19 18 17 16 15 14 13 12 11]


5-Write a NumPy program to extract all odd numbers from an array.

In [18]:
x=np.arange(1,11)
print(x)
x[::]
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[20 19 18 17 16 15 14 13 12 11]
