# Array

In [2]:
import numpy as np
x=[1,2,3,4,5]#list
print(x)
print(type(x))
y=np.array(x)
print(y)#array
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#user input and creating array
l=[]
for i in range(1,6):
    int_1=int(input("Enter:"))
    l.append(int_1)
print(np.array(l))    

[1 2 3 4 5]


In [4]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [5]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [6]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Zeros

In [7]:
ar_zero=np.zeros(10)
print(ar_zero)#  1-dimensional
print()
ar_zero1=np.zeros((3,4))
print(ar_zero1)#  2-dimensional

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [8]:
ar_one=np.ones(5)
print(ar_one)

[1. 1. 1. 1. 1.]


# Empty

In [9]:
ar_em=np.empty(0)
print(ar_em)

[]


In [10]:
ar_em=np.empty(10)#bydefalt last array le leta h
print(ar_em)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Range

In [11]:
ar_rn=np.arange(1,11)
print(ar_rn)

[ 1  2  3  4  5  6  7  8  9 10]


# Diagonal

In [12]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linspace

In [14]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


# Random
 - Rand()
 - Randn()
 - Ranf()
 - Randint()# Min Max Total_value

In [15]:
var=np.random.rand(3)
print(var)

[0.53882004 0.93967371 0.3797987 ]


In [16]:
var1=np.random.rand(3,4)
print(var1)

[[0.38377209 0.16484456 0.08058187 0.85983706]
 [0.84220787 0.61570881 0.52552205 0.47720256]
 [0.59252552 0.02558002 0.06557944 0.94076645]]


In [17]:
var2=np.random.randn(3)
print(var2)

[ 0.40369372 -1.7180709   0.15974354]


In [18]:
var3=np.random.ranf(4)
print(var3)

[0.74887694 0.62536464 0.77071082 0.76656967]


In [19]:
var4=np.random.randint(1,10,5)
print(var4)

[6 5 4 7 7]


# Data Type

In [22]:
var=np.array([1,2,3,4,5])
print("Data type :",var.dtype)

Data type : int32


# Arithmetic Operation

In [16]:
import numpy as np
var=np.array([1,2,3,4])
varadd=var+5
print(varadd)

[6 7 8 9]


In [2]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varadd=var1+var2
print(varadd)

[ 2  4  6  8 10]


In [13]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varadd=np.add(var1,var2)
print(varadd)

[ 2  4  6  8 10]


In [14]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varadd=np.add(var1,5)
print(varadd)

[ 6  7  8  9 10]


In [3]:
var=np.array([9,8,6,7,5])
varsub=var-4
print(varsub)

[5 4 2 3 1]


In [4]:
var=np.array([9,8,6,7,5])
varmult=var*4
print(varmult)

[36 32 24 28 20]


In [8]:
var=np.array([5,10,15,20,25])
vardiv=var/5
print(vardiv)

[1. 2. 3. 4. 5.]


# 2D Array

In [19]:
var1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
var2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var1)
print()
print(var2)
print()
varadd=var1+var2
print(varadd)

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
